export type ClaimReportPayload = {
  claimId: string;
  status: string;
  claimedDisplay: string;
  approvedDisplay: string;
  careNavigatorNotes: string;
  patientName?: string;
  memberId?: string;
  treatmentDate?: string;
};

export function formatClaimReportText(p: ClaimReportPayload): string {
  const generated = new Date().toISOString();
  const lines = [
    "════════════════════════════════════════════════════════════",
    "                      PLUM OPD",
    "               Adjudication summary report",
    "════════════════════════════════════════════════════════════",
    "",
    `Claim ID:          ${p.claimId}`,
    `Decision / status: ${p.status}`,
    ...(p.patientName ? [`Member / patient:  ${p.patientName}`] : []),
    `Generated (UTC):   ${generated}`,
    "",
    "────────────────────────────────────────────────────────────",
    " FINANCIAL SUMMARY",
    "────────────────────────────────────────────────────────────",
    `Amount claimed:    ${p.claimedDisplay}`,
    `Amount approved:   ${p.approvedDisplay}`,
    "",
    "────────────────────────────────────────────────────────────",
    " CARE NAVIGATOR NOTES (AI)",
    "────────────────────────────────────────────────────────────",
    (p.careNavigatorNotes.trim() || "(No notes recorded.)"),
    "",
    "────────────────────────────────────────────────────────────",
    "This report is generated by Plum OPD for operations and audit.",
    "It does not replace master policy or contract language.",
    "════════════════════════════════════════════════════════════",
  ];
  return lines.join("\n");
}

/** Download a formatted plain-text report (.txt). */
export function downloadClaimReport(p: ClaimReportPayload): void {
  const text = formatClaimReportText(p);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const safeId = p.claimId.replace(/[^a-zA-Z0-9-_]/g, "").slice(0, 24) || "claim";
  a.download = `plum-opd-report-${safeId}.txt`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
